// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// ValidateStartTime validates start time format
func (r *GPUUsageQueryRequest) ValidateStartTime() bool {
	return r.StartTime != ""
}

// ValidateEndTime validates end time format
func (r *GPUUsageQueryRequest) ValidateEndTime() bool {
	return r.EndTime != ""
}

// HasFilter checks if any filter is set
func (r *GPUUsageQueryRequest) HasFilter() bool {
	return r.UserID != "" || r.TeamID != "" || r.ProjectID != "" ||
		r.PodName != "" || r.ResourceType != ""
}

// IsAggregateQuery checks if this is an aggregate query
func (r *GPUUsageQueryRequest) IsAggregateQuery() bool {
	return r.AggregateBy != ""
}

// GetTotalGPUs calculates total GPUs from records
func (d *GPUUsageData) GetTotalGPUs() int {
	total := 0
	for _, record := range d.Records {
		total += record.GPUCount
	}
	return total
}

// IsHealthy checks if health check shows healthy status
func (h *HealthCheckResponse) IsHealthy() bool {
	return h.Status == "healthy" || h.Status == "ok"
}

// GetAverageGPUHours calculates average GPU hours per record
func (d *GPUUsageData) GetAverageGPUHours() float64 {
	if d.RecordCount == 0 {
		return 0.0
	}
	return d.TotalGPUHours / float64(d.RecordCount)
}

// HasAggregates checks if aggregate data exists
func (a *GPUUsageAggregateData) HasAggregates() bool {
	return len(a.Aggregates) > 0
}

// GetDimensionCount returns number of dimensions in aggregate item
func (a *GPUUsageAggregateItem) GetDimensionCount() int {
	if a.Dimensions == nil {
		return 0
	}
	return len(a.Dimensions)
}

type GPUUsageData struct {
	TotalGPUHours float64          `json:"total_gpu_hours"`
	TotalCount    int              `json:"total_count"`
	RecordCount   int              `json:"record_count"`
	Page          int              `json:"page"`
	PageSize      int              `json:"page_size"`
	TotalPages    int              `json:"total_pages"`
	Records       []GPUUsageRecord `json:"records"`
}

// GPUUsageAggregateData 聚合结果响应（✅ STORY-13-02 新增）
type GPUUsageAggregateData struct {
	TotalCount      int                     `json:"total_count"`
	QueryType       string                  `json:"query_type"`                // "aggregate"
	TimeGranularity string                  `json:"time_granularity,optional"` // "day", "hour", "minute", "none"
	Aggregates      []GPUUsageAggregateItem `json:"aggregates"`
}

// GPUUsageAggregateItem 聚合项（✅ STORY-13-02 新增）
type GPUUsageAggregateItem struct {
	TimeBucket    *string           `json:"time_bucket,optional"` // RFC3339格式
	Dimensions    map[string]string `json:"dimensions"`           // 动态维度
	TotalGPUHours float64           `json:"total_gpu_hours"`
	RecordCount   int               `json:"record_count"`
	UniquePods    int               `json:"unique_pods"`
}

type GPUUsageQueryRequest struct {
	StartTime    string `json:"start_time,optional" form:"start_time,optional"`
	EndTime      string `json:"end_time,optional" form:"end_time,optional"`
	UserID       string `json:"user_id,optional" form:"user_id,optional"`
	TeamID       string `json:"team_id,optional" form:"team_id,optional"`
	ProjectID    string `json:"project_id,optional" form:"project_id,optional"`
	PodName      string `json:"pod_name,optional" form:"pod_name,optional"`
	ResourceType string `json:"resource_type,optional" form:"resource_type,optional"`
	// ✅ STORY-13-02 新增：聚合维度（逗号分隔，最多 2 级）
	AggregateBy string `json:"aggregate_by,optional" form:"aggregate_by,optional"`
	Page        int    `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize    int    `json:"page_size,optional,default=20" form:"page_size,optional,default=20"`
}

type GPUUsageQueryResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	// ✅ STORY-13-02 修改：支持两种数据格式（详细记录、聚合结果）
	Data interface{} `json:"data,optional"` // GPUUsageData | GPUUsageAggregateData
}

type GPUUsageRecord struct {
	ResourceID   string  `json:"resource_id"`
	PodName      string  `json:"pod_name"`
	PodNamespace string  `json:"pod_namespace"`
	ResourceType string  `json:"resource_type"`
	GPUCount     int     `json:"gpu_count"`
	GPUProduct   string  `json:"gpu_product"`
	GPUHours     float64 `json:"gpu_hours"`
	UsageStartAt string  `json:"usage_start_at"`
	UsageEndAt   string  `json:"usage_end_at,optional"`
	// ✅ v2.0: Real-time calculation timestamp
	CalculatedAt string `json:"calculated_at"`
	Status       string `json:"status"`
}

type HealthCheckResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Uptime  string `json:"uptime"`
}
